name: Publish version

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # we need to fetch full git in-order for lerna to
      # detect rc count
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0

      - name: Install packages
        run: yarn install

      - name: Create local changes
        run: npm version patch --no-git-tag-version

      - name: Publish
        run: yarn publish
