name: Publish version

on:
  push:
    branches:
      - test/ci

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # we need to fetch full git in-order for lerna to
      # detect rc count
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0

      # - name: Setup npm
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
      #   env:
      #     NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Install packages
        run: yarn install

      - name: Build
        run: yarn build

      # - name: Publish
      #   run: yarn publish:patch

      - name: Push tag
        run: git push && git push --tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
